#!/bin/sh
exe=$(which clang-format)

if [ -n "$exe" ]
then
  IFS=$'\n'
  for line in $(git status -s)
  do
    if [[ $line == A* || $line == M* ]]
    then
      if [[ $line == *.c || $line == *.cc || $line == *.h || $line == *.cpp ]]
      then
        clang-format -i -style=file $(pwd)/${line:3}
        git add $(pwd)/${line:3}
      fi
    fi
  done
else
  echo "WARNING: clang-format was not found, cannot format files!"
fi