#ifndef UNICORN_WINDOW_MANAGER_ADAPTERS_GLFW_CONFIG_HPP
#define UNICORN_WINDOW_MANAGER_ADAPTERS_GLFW_CONFIG_HPP

#define WINDOW_MANAGER_ADAPTER  glfw::Adapter

#include <unicorn/window_manager/adapters/glfw/Adapter.hpp>

#endif /* UNICORN_WINDOW_MANAGER_ADAPTERS_GLFW_CONFIG_HPP */
